apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stage-

commonLabels:
    app: my-app
    env: stage

bases:
  - ../../../base

resources:
  - ingress.yaml

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

namespace: stage