apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
    env: stage
  name: stage-my-web-app-service
  namespace: stage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app
    env: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    env: stage
  name: stage-my-app-deployment
  namespace: stage
  template:
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      env: stage
  template:
    metadata:
      labels:
        app: my-app
        env: stage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: my-app
    env: stage
  name: stage-my-app
  namespace: stage
spec:
  rules:
  - host: stage-my-app.com
    http:
      paths:
      - backend:
          service:
            name: my-app
            port:
              number: 80
        path: /
        pathType: Prefix
