apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: kymc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kymc
      app.kubernetes.io/instance: kymc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kymc
        app.kubernetes.io/instance: kymc
    spec:
      serviceAccountName: kymc
      securityContext: {
        runAsNonRoot: true
      }
      containers:
        - name: kymc
          image: "kymc:6.01.0677"
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /manage/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              port: 8080
              path: /manage/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 120
          envFrom:
            - secretRef:
               name: crypt-db
            - secretRef:
               name: aws-kms-service
            - configMapRef:
                name: kymc-base-config
            - configMapRef:
                name: kymc-overlays-config  
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SV_METRICS_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetrycollector-gateway-collector.otel-perf-cc.svc.cluster.local:4318
            - name: RESTART_TOGGLE
              value: "true"
