name: Validate Kubernetes Manifests

on:
  pull_request:
    branches: [ main ]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fairwindsops/polaris/.github/actions/setup-polaris@master
        with:
          version: 5.0.0
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kustomize
          kubeconform: '0.5.0'
          kustomize: '4.5.7'
      - run: |
          echo "******************** Validating Dev Manifests ***********************"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-dev -o dev_consolidated_manifest.yaml
          echo -e "--------- CONSOLIDATED MANIFEST ---------- \n$(cat dev_consolidated_manifest.yaml)"
          polaris audit --audit-path ./dev_consolidated_manifest.yaml --format=pretty --set-exit-code-on-danger --set-exit-code-below-score 80
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-dev | kubeconform -verbose
          polaris audit --audit-path ./dev_consolidated_manifest.yaml --format=pretty --set-exit-code-on-danger --set-exit-code-below-score 80 --config "apps/my-web-app/validation/custom/polaris/custom-check.yaml"
      - run: |
          echo "******************** Validating Test Manifests ***********************"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-test -o test_consolidated_manifest.yaml
          echo -e "--------- CONSOLIDATED MANIFEST ---------- \n$(cat test_consolidated_manifest.yaml)"
          polaris audit --audit-path ./test_consolidated_manifest.yaml --format=pretty --set-exit-code-on-danger --set-exit-code-below-score 80
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-test | kubeconform -verbose
          polaris audit --audit-path ./test_consolidated_manifest.yaml --format=pretty --set-exit-code-on-danger --set-exit-code-below-score 80 --config "apps/my-web-app/validation/custom/polaris/custom-check.yaml"
          
