name: Validate Kubernetes Manifests

on:
  pull_request:
    branches: [ main ]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kustomize
          kubeconform: '0.5.0'
          kustomize: '4.5.7'
      - run: |
          kustomize build apps/my-web-app/overlays/environments/stage | kubeconform -verbose
          kustomize build apps/my-web-app/overlays/environments/prod | kubeconform -verbose
