name: Validate Kubernetes Manifests

on:
  pull_request:
    branches: [ main ]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kustomize
            conftest
          kubeconform: '0.5.0'
          kustomize: '4.5.7'
          conftest: '0.50.0'
      - run: |
          echo "******************** Validating Dev Manifests ***********************"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-dev -o dev_consolidated_manifest.yaml
          echo -e "--------- CONSOLIDATED MANIFEST ---------- \n$(cat dev_consolidated_manifest.yaml)"
          # conftest test --update github.com/instrumenta/policies.git//kubernetes dev_consolidated_manifest.yaml
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-dev | kubeconform -verbose | conftest test
      - run: |
          echo "******************** Validating Test Manifests ***********************"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-test -o test_consolidated_manifest.yaml
          echo -e "--------- CONSOLIDATED MANIFEST ---------- \n$(cat test_consolidated_manifest.yaml)"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-test | kubeconform -verbose | conftest test -
      - name: Conftest test against changed files
        uses: instrumenta/conftest-action@master
        with:
          files: dev_consolidated_manifest.yaml
          policy: conftest_policies
